- /usr/sbin is not in default PATH
Changed files:
    munin-plugins.patch -> 1.35

diff --git a/munin-plugins.patch b/munin-plugins.patch
--- a/munin-plugins.patch
+++ b/munin-plugins.patch
@@ -1217,3 +1217,86 @@ diff -Naur munin-1.3.4/plugins/node.d.linux/nfsd.in munin-1.3.4-p/plugins/node.d
 +    fi
  done
 -
+--- munin-1.4.0/plugins/node.d/ntp_offset.in~	2009-11-27 12:17:11.000000000 +0100
++++ munin-1.4.0/plugins/node.d/ntp_offset.in	2009-12-16 13:28:05.942149904 +0100
+@@ -38,9 +38,9 @@
+ =cut
+ 
+ do_autoconf () {
+-    ntpq -c help >/dev/null 2>&1 || { echo 'no (no ntpq program)'; exit 0; }
++    /usr/sbin/ntpq -c help >/dev/null 2>&1 || { echo 'no (no ntpq program)'; exit 0; }
+     
+-    case "$(ntpq -n -p 2>/dev/null | wc -l)" in
++    case "$(/usr/sbin/ntpq -n -p 2>/dev/null | wc -l)" in
+ 	0)
+             echo 'no (unable to list peers)'
+ 	    exit 0
+@@ -57,7 +57,7 @@
+ }
+ 
+ do_config () {
+-    syspeer="$(ntpq -n -p | grep '^[*o]')"
++    syspeer="$(/usr/sbin/ntpq -n -p | grep '^[*o]')"
+ 
+     set - $syspeer
+ 
+@@ -89,7 +89,7 @@
+ 
+ do_ () {
+     # Fetch operation
+-    syspeer="$(ntpq -n -p | grep '^[*o]')"
++    syspeer="$(/usr/sbin/ntpq -n -p | grep '^[*o]')"
+ 
+     set - $syspeer
+ 
+--- munin-1.4.0/plugins/node.d/ntp_kernel_err.in~	2009-11-27 12:17:10.000000000 +0100
++++ munin-1.4.0/plugins/node.d/ntp_kernel_err.in	2009-12-16 13:29:00.494146341 +0100
+@@ -33,7 +33,7 @@
+ 
+ if [ "$1" = "autoconf" ]; then
+     # Not all ntpdc's are equal
+-    ntpdc -c kern 2>/dev/null | 
++    /usr/sbin/ntpdc -c kern 2>/dev/null | 
+     awk 'BEGIN { ev=1; }
+          /^estimated error:/ { ev=0; } 
+          END { if (ev == 0) { print "yes";} else { print "no"; } exit ev; }'
+@@ -51,4 +51,4 @@
+ fi
+ 
+ echo -n 'ntp_err.value '
+-ntpdc -c kern | awk '/^estimated error:/ { print $3 }'
++/usr/sbin/ntpdc -c kern | awk '/^estimated error:/ { print $3 }'
+--- munin-1.4.0/plugins/node.d/ntp_kernel_pll_freq.in~	2009-12-15 20:45:10.715504269 +0100
++++ munin-1.4.0/plugins/node.d/ntp_kernel_pll_freq.in	2009-12-16 13:29:26.464147058 +0100
+@@ -39,7 +39,7 @@
+ # $Id$
+ 
+ if [ "$1" = "autoconf" ]; then
+-    ntpdc -c kern 2>/dev/null | 
++    /usr/sbin/ntpdc -c kern 2>/dev/null | 
+     awk 'BEGIN { ev=1; }
+          /^pll frequency:/ { ev=0; } 
+          END { if (ev == 0) { print "yes";} else { print "no"; } exit ev; }'
+@@ -64,4 +64,4 @@
+ fi
+ 
+ echo -n 'ntp_pll_freq.value '
+-ntpdc -c kern | awk -v fcomp=$fcomp '/^pll frequency:/ { print $3 + fcomp }'
++/usr/sbin/ntpdc -c kern | awk -v fcomp=$fcomp '/^pll frequency:/ { print $3 + fcomp }'
+--- munin-1.4.0/plugins/node.d/ntp_kernel_pll_off.in~	2009-11-27 12:17:10.000000000 +0100
++++ munin-1.4.0/plugins/node.d/ntp_kernel_pll_off.in	2009-12-16 13:29:45.228087885 +0100
+@@ -32,7 +32,7 @@
+ # $Id$
+ 
+ if [ "$1" = "autoconf" ]; then
+-    ntpdc -c kern 2>/dev/null | 
++    /usr/sbin/ntpdc -c kern 2>/dev/null | 
+     awk 'BEGIN { ev=1; }
+          /^pll offset:/ { ev=0; } 
+          END { if (ev == 0) { print "yes";} else { print "no"; } exit ev; }'
+@@ -50,4 +50,4 @@
+ fi
+ 
+ echo -n 'ntp_pll_off.value '
+-ntpdc -c kern | awk '/^pll offset:/ { print $3 }'
++/usr/sbin/ntpdc -c kern | awk '/^pll offset:/ { print $3 }'
